### PR TITLE
Pass on HTTP Path when calling functions asynchronously

### PR DESCRIPTION
**Pull request by jpauwels**
This commit fixes faas issue https://github.com/openfaas/faas/issues/1035.
It requires the vendored faas queue.Request struct to be updated to the latest version in the faas repo.

Signed-off-by: Johan Pauwels <jpauwels@users.noreply.github.com>

## Motivation and Context

- [x] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))

## How Has This Been Tested?
Local (macOS) and server (Ubuntu) deployment with Docker Swarm.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by alexellis** [comment]
Hi Johan thank you for working on this. 

Please could you show end-to-end testing using the following? https://github.com/alexellis/tensorflow-serving-openfaas

Thanks,

Alex

**Comment by jpauwels** [comment]
I've cloned your TS serving repo and can replicate the given example out of the box. Are you interested in any particular log files?

**Comment by jpauwels** [comment]
Here's the requestbin: https://requestbin.fullcontact.com/142ob7k1?inspect

**Comment by alexellis** [comment]
That's great

**Comment by alexellis** [comment]
Hi @jpauwels a real email address is required for the sign-off.

```
Signed-off-by: Johan Pauwels [jpauwels@users.noreply.github.com](mailto:jpauwels@users.noreply.github.com)
```

This should be your qmul or a personal address. Please amend with:

```
git config user.name
git commit -s --amend
```

Thanks

**Comment by jpauwels** [comment]
Added email and rebased

**Comment by alexellis** [comment]
So do we just need a new release of the queue worker and that is it?

**Comment by jpauwels** [comment]
> So do we just need a new release of the queue worker and that is it?

Indeed

**Comment by jpauwels** [comment]
> So do we just need a new release of the queue worker and that is it?

The necessary work in the main repo has been done by @telackey in https://github.com/openfaas/faas/commit/decf9addb37bec43e1ae7b91fb860837671597b6 six months ago. He might be able to tell you what the motivation was for those changes.

**Comment by alexellis** [comment]
I worked on those changes to and actually finished the patch. If you can find the old PRs you'll see it. I'm just asking you what packaging you think we need to do as a result of your change?

**Comment by jpauwels** [comment]
Even better then. So yes, just release a new version of the queue worker and change the docker-compose.yml in the main repo and that should be it.

**Comment by alexellis** [comment]
I'll cut a new release. Would you be able to do the updates for docker swarm and for Kubernetes? if you have any questions I'm sure people would be more than willing to help on Slack.

**Comment by jpauwels** [comment]
Looks like it's being done, which is good cause I don't really know what you mean by that. I've never used Kubernetes btw and my Swarm just consists of a single node.

**Pull request merged**
