### PR TITLE
Use ReadConfig object for env config, add write_debug for queue worker

### PR DESCRIPTION
**Pull request by ericstoekl**
Include write_debug env variable option, default false

Signed-off-by: Eric Stoekl <ems5311@gmail.com>

This change adds a similar Config object that the `faas` repo features ([see here](https://github.com/openfaas/faas/blob/d3d320dc33262fdc63c00440f8b800219849ac3d/gateway/types/readconfig.go#L56)). Env variables are parsed into a `ReadConfig` object, which is later read from in the `main` function.

## Description

In addition, the `write_debug` option is now available, which is false by default. If you set it to `true` or `1`, you will see the output of the asynchronously invoked function in the logs for the `func_queue-worker` container.

## Motivation and Context

- [X] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))
https://github.com/openfaas/nats-queue-worker/issues/11

## How Has This Been Tested?

Test file `readconfig_test.go` was added at the root of the repo.

Execution of these tests was added to the `Dockerfile`.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the code style of this project.
- [X] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [X] I have signed-off my commits with `git commit -s`
- [X] I have added tests to cover my changes.
- [X] All new and existing tests passed.

### CODE REVIEW

**Comment by ericstoekl** [comment]
I would like to know where the proper place to change the documentation would be. Would be good to make note that we added the `write_debug` to the queue-worker as well.

**Comment by alexellis** [comment]
Start with the readme file and helm chart. Then I'd say look at where we cover the queue worker in the docs site.

**Comment by ericstoekl** [comment]
Added documentation to the github.com/openfaas/docs repo: https://github.com/openfaas/docs/pull/43

**Comment by alexellis** [comment]
Thanks, have you updated the helm chart too?

Alex

**Comment by alexellis** [comment]
@mrtind please could you test this code and do a code review to make sure all variables are still loaded into the correct places?

Alex

**Comment by mrtind** [comment]
For now i was only able to build the image successfully.

**Comment by ericstoekl** [comment]
@alexellis helm chart PR submitted here: https://github.com/openfaas/faas-netes/pull/246

**Comment by alexellis** [comment]
Thanks for testing.

**Pull request merged**
